# Generated by Django 3.0 on 2021-07-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
