# Generated by Django 3.0 on 2021-08-02 09:12

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privilege_manager", "0005_openidloginprevention"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel("Billing", "Subscription"),
        migrations.RemoveField(model_name="subscription", name="expiry_date",),
        migrations.RemoveField(model_name="subscription", name="user",),
        migrations.AddField(
            model_name="subscription",
            name="end_timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscription_groups",
                to="privilege_manager.Group",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="start_timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 8, 2, 9, 12, 47, 168990)
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_type",
            field=models.CharField(
                choices=[("INDIVIDUAL", "INDIVIDUAL"), ("COMPANY", "COMPANY")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscription_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
