# Generated by Django 3.0 on 2021-07-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billing_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
