# Generated by Django 3.0 on 2021-08-02 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_auto_20210802_0930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="start_timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 8, 2, 9, 41, 48, 709002, tzinfo=utc)
            ),
        ),
    ]
