# Generated by Django 3.0 on 2021-08-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_auto_20210825_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
