# Generated by Django 3.0 on 2020-01-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity_provider", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="oidp_code",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="user_id",
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
