# Generated by Django 3.0 on 2020-02-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity_provider', '0002_auto_20200123_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='oidp_code',
            new_name='oidc_code',
        ),
    ]
