# Generated by Django 3.0 on 2022-03-08 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('identity_provider', '0006_apikey_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='wms_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
