# Generated by Django 4.2 on 2024-09-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('identity_provider', '0010_alter_apikey_scope'), ('identity_provider', '0011_alter_apikey_scope')]

    dependencies = [
        ('identity_provider', '0009_apikey_expiry_apikey_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='scope',
            field=models.CharField(choices=[('Management', 'management'), ('Resource', 'resource')], default='resource', max_length=50),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='scope',
            field=models.CharField(choices=[('management', 'Management'), ('resource', 'Resource')], default='resource', max_length=50),
        ),
    ]
