# Generated by Django 4.2 on 2024-09-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_provider', '0010_alter_apikey_scope_squashed_0011_alter_apikey_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='scope',
            field=models.CharField(choices=[('management', 'Management'), ('resource', 'Resource')], max_length=50),
        ),
    ]
