# Generated by Django 4.2 on 2024-05-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorizations", "0004_alter_resource_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="path",
            field=models.CharField(blank=True, default="", verbose_name="path"),
        ),
    ]
