# Generated by Django 4.2 on 2024-10-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0007_alter_resource_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.CharField(blank=True, null=True, verbose_name='Description of the upstream service'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(blank=True, null=True, verbose_name='URL for the upstream service'),
        ),
    ]
