# Generated by Django 3.0 on 2020-02-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20200122_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legacy_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
