# Generated by Django 3.0 on 2020-02-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_user_legacy_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
