# Generated by Django 3.0 on 2021-07-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_user_secondary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_consent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
