# Generated by Django 3.0 on 2021-07-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_user_secondary_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='consent',
            new_name='subscription',
        )
    ]
