# Generated by Django 4.2 on 2024-05-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorizations", "0001_initial"),
        (
            "user_management",
            "0013_remove_user_company_name_remove_user_subscription_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ManyToManyField(blank=True, to="authorizations.role"),
        ),
    ]
