# Generated by Django 3.0 on 2020-06-22 12:12

from django.db import migrations

from apps.global_configuration.models import GlobalConfiguration


def init_configuration(apps, schemas):
    from django.conf import settings

    config = GlobalConfiguration.load()
    config.map_redirect_url = settings.MAP_URL
    config.save()


class Migration(migrations.Migration):
    dependencies = [
        ("global_configuration", "0001_initial"),
    ]

    operations = [migrations.RunPython(init_configuration)]
