# Generated by Django 3.0 on 2020-01-21 08:11

from django.db import migrations


def add_default_groups(apps, schema_editor):

    Group = apps.get_model('privilege_manager', 'Group')

    free_group = Group(name='free')
    free_group.save()

    pro_group = Group(name='pro')
    pro_group.save()

    enterprise_group = Group(name='enterprise')
    enterprise_group.save()

    hub_group = Group(name='hub')
    hub_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('privilege_manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_groups),
    ]
