# Generated by Django 3.0 on 2021-11-16 15:26
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("privilege_manager", "0005_openidloginprevention"),
    ]

    operations = [
        migrations.RemoveField(model_name="group", name="users",),
    ]
