# Generated by Django 4.2 on 2024-05-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorizations", "0001_initial"),
        ("privilege_manager", "0008_rename_groups_openidloginprevention_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="role",
            field=models.ManyToManyField(blank=True, to="authorizations.role"),
        ),
    ]
