# Generated by Django 3.0 on 2021-08-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0003_companymanagementmodel_individualmanagementmodel"),
    ]

    operations = [
        migrations.DeleteModel(name="CompanyManagementModel",),
        migrations.DeleteModel(name="IndividualManagementModel",),
    ]
