# Generated by Django 3.0 on 2021-08-25 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0014_subscription_groups'),
        ('administration', '0007_auto_20210825_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscription',
            name='company',
            field=models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Company'),
        ),
        migrations.AlterField(
            model_name='individualsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='companysubscription',
            constraint=models.UniqueConstraint(fields=('company',), name='unique_company_per_subscription'),
        ),
    ]
